// Generated from the handoff icon set (80 Lucide icons). Add a name here to make it available to <Icon name="..." />.
import type { LucideIcon } from "lucide-react";
import {
  Apple,
  ArchiveRestore,
  ArrowLeft,
  ArrowRight,
  Baby,
  Beef,
  Bell,
  BookOpen,
  Calendar,
  CalendarDays,
  Camera,
  Carrot,
  Check,
  ChefHat,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  ClipboardList,
  Clock,
  CookingPot,
  CupSoda,
  Egg,
  Ellipsis,
  Filter,
  Fish,
  Flame,
  Heart,
  History,
  House,
  IceCreamCone,
  Image,
  Info,
  LayoutGrid,
  Leaf,
  List,
  ListChecks,
  MessageCircle,
  Mic,
  Milk,
  Minus,
  NotebookPen,
  Package,
  Pause,
  Pencil,
  Play,
  Plus,
  Receipt,
  RefreshCw,
  Refrigerator,
  Salad,
  Sandwich,
  Scale,
  Search,
  Send,
  Settings,
  ShoppingBasket,
  ShoppingCart,
  Snowflake,
  Soup,
  Sparkles,
  Star,
  Store,
  Sun,
  Tag,
  ThumbsDown,
  ThumbsUp,
  Timer,
  Trash2,
  TriangleAlert,
  Truck,
  Upload,
  User,
  Users,
  Utensils,
  UtensilsCrossed,
  Vote,
  Wheat,
  X,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  "apple": Apple,
  "archive-restore": ArchiveRestore,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "baby": Baby,
  "beef": Beef,
  "bell": Bell,
  "book-open": BookOpen,
  "calendar": Calendar,
  "calendar-days": CalendarDays,
  "camera": Camera,
  "carrot": Carrot,
  "check": Check,
  "chef-hat": ChefHat,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "circle-check": CircleCheck,
  "clipboard-list": ClipboardList,
  "clock": Clock,
  "cooking-pot": CookingPot,
  "cup-soda": CupSoda,
  "egg": Egg,
  "ellipsis": Ellipsis,
  "filter": Filter,
  "fish": Fish,
  "flame": Flame,
  "heart": Heart,
  "history": History,
  "house": House,
  "ice-cream-cone": IceCreamCone,
  "image": Image,
  "info": Info,
  "layout-grid": LayoutGrid,
  "leaf": Leaf,
  "list": List,
  "list-checks": ListChecks,
  "message-circle": MessageCircle,
  "mic": Mic,
  "milk": Milk,
  "minus": Minus,
  "notebook-pen": NotebookPen,
  "package": Package,
  "pause": Pause,
  "pencil": Pencil,
  "play": Play,
  "plus": Plus,
  "receipt": Receipt,
  "refresh-cw": RefreshCw,
  "refrigerator": Refrigerator,
  "salad": Salad,
  "sandwich": Sandwich,
  "scale": Scale,
  "search": Search,
  "send": Send,
  "settings": Settings,
  "shopping-basket": ShoppingBasket,
  "shopping-cart": ShoppingCart,
  "snowflake": Snowflake,
  "soup": Soup,
  "sparkles": Sparkles,
  "star": Star,
  "store": Store,
  "sun": Sun,
  "tag": Tag,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  "timer": Timer,
  "trash-2": Trash2,
  "triangle-alert": TriangleAlert,
  "truck": Truck,
  "upload": Upload,
  "user": User,
  "users": Users,
  "utensils": Utensils,
  "utensils-crossed": UtensilsCrossed,
  "vote": Vote,
  "wheat": Wheat,
  "x": X,
};
