window.CLM = {
  week: 'Week of August 24',
  people: { lauren: { name: 'Lauren', color: 'sage' }, joe: { name: 'Joe', color: 'slate' }, leidy: { name: 'Leidy', color: 'terra' } },
  meals: {
    tacos: { title: 'Taco Tuesday', description: 'Al pastor pork tacos with queso fresco, lettuce, tomato, salsa — with black beans and sweet corn sides.', method: 'Skillet', time: '30 min', healthy: 7, delicious: 9, cost: '~$22', stars: 5, onSale: true, why: ['5-star family favorite', 'Al pastor pork on sale, $3.49/lb', 'Leftovers cover Tuesday'], leftovers: 'Tue: taco-salad bowls with beans, corn, crushed chips', ingredients: [['2 lbs', 'marinated pork taco meat', 'sale'], ['12', 'small tortillas', 'list'], ['1 head', 'lettuce', 'list'], ['1', 'queso fresco 10 oz', 'sale'], ['1 jar', 'salsa', 'sale'], ['1 can', 'black beans', 'list'], ['6 ears', 'sweet corn', 'sale']] },
    chops: { title: 'Sheet Pan Pork Chops with Roasted Veggies', description: 'Center-cut pork chops roasted with potatoes, green beans and onion, seasoned with smoked paprika and thyme.', method: 'Sheet pan', time: '40 min', healthy: 8, delicious: 8, cost: '~$18', onSale: true, why: ['Pork chops on sale, $2.29/lb', 'One pan, 10 min hands-on', 'Yukon golds 99¢/lb'], leftovers: 'Slice over a green salad, or chop into fried rice', ingredients: [['5', 'center-cut pork chops', 'sale'], ['1.5 lbs', 'Yukon gold potatoes', 'sale'], ['1 lb', 'green beans', 'list'], ['1', 'white onion', 'list'], ['2 tsp', 'smoked paprika', 'have'], ['1 tsp', 'dried thyme', 'have'], ['3 tbsp', 'olive oil', 'have']] },
    shrimp: { title: 'Basil Shrimp with Feta and Orzo', description: 'Warm orzo tossed with tomatoes, green onion, basil, lemon, feta and sautéed shrimp.', method: 'Skillet', time: '30 min', healthy: 8, delicious: 9, cost: '~$26', stars: 5, onSale: true, why: ['Joe asked for it Monday', 'XL shrimp on sale, $9.99/lb', '5-star favorite'], leftovers: 'Sat lunch: serve cold as an orzo salad', ingredients: [['1.5 lbs', 'XL shrimp 16/20', 'sale'], ['1 lb', 'orzo', 'list'], ['1.5 lbs', 'ripe tomatoes', 'list'], ['1 bunch', 'fresh basil', 'list'], ['6 oz', 'feta', 'list'], ['2', 'lemons', 'sale']] },
    chicken: { title: 'Sheet Pan Citrus Chicken Thighs', description: 'Boneless thighs roasted with orange and lemon, garlic, Roma tomatoes and green beans.', method: 'Sheet pan', time: '45 min', healthy: 8, delicious: 8, cost: '~$20', why: ['Lemons 99¢/lb', 'Makes 2 days of leftovers', 'Favorite protein: thighs'], leftovers: 'Sun: shred into wraps with deli cheese', ingredients: [['2 lbs', 'boneless chicken thighs', 'list'], ['2', 'navel oranges', 'list'], ['1 lb', 'Roma tomatoes', 'list'], ['1 lb', 'green beans', 'list'], ['1 head', 'garlic', 'list']] },
    salmon: { title: 'Sheet Pan Salmon with Lemon Potatoes', description: 'Salmon fillets roasted over crispy lemon potatoes and green beans.', method: 'Sheet pan', time: '35 min', healthy: 9, delicious: 8, cost: '~$30', onSale: true, why: ['You asked for salmon on Wednesday', 'Atlantic salmon on sale, $8.99/lb', 'Same pan and sides as the pork chops'], leftovers: 'Flake into rice bowls with cucumber', ingredients: [['2.5 lbs', 'Atlantic salmon fillet', 'sale'], ['1.5 lbs', 'Yukon gold potatoes', 'sale'], ['1 lb', 'green beans', 'list'], ['2', 'lemons', 'sale']] },
    meatballs: { title: 'Instant Pot Meatballs and Marinara', description: 'Frozen Italian meatballs simmered in marinara over spaghetti, with a big salad.', method: 'Instant Pot', time: '25 min', healthy: 6, delicious: 8, cost: '~$12', why: ['Uses the meatballs in the freezer', 'Ragu 2/$5 this week', 'Lowest effort option'], leftovers: 'Meatball subs with deli cheese', ingredients: [['1 tray', 'Italian meatballs', 'have'], ['1 jar', 'marinara', 'sale'], ['1 lb', 'spaghetti', 'have'], ['1 bag', 'salad greens', 'list']] },
    soup: { title: 'Instant Pot Chicken Tortilla Soup', description: 'Rich, spiced chicken soup with black beans, corn, and all the Tex-Mex toppings.', method: 'Instant Pot', time: '35 min', healthy: 8, delicious: 9, cost: '~$14', stars: 5, why: ['5-star favorite, last made in March', 'Black beans 2/$5', 'Two days of leftovers'], leftovers: 'Pour over rice for a tortilla soup bowl', ingredients: [['2.5 lbs', 'chicken thighs', 'list'], ['1 can', 'black beans', 'sale'], ['1 can', 'fire-roasted tomatoes', 'list'], ['4 cups', 'chicken broth', 'list'], ['2', 'avocados', 'list']] },
    tofu: { title: 'Bok Choy and Tofu Stir Fry', description: 'Crispy tofu, baby bok choy and garlic in a quick ginger-soy sauce over rice.', method: 'Skillet', time: '25 min', healthy: 9, delicious: 7, cost: '~$11', onSale: true, why: ['Vegetarian, as asked', 'Baby bok choy on sale, $1.49', 'Uses rice on hand'], leftovers: 'Fried rice with an egg', ingredients: [['2 blocks', 'extra-firm tofu', 'list'], ['4', 'baby bok choy', 'sale'], ['3 cloves', 'garlic', 'list'], ['2 cups', 'rice', 'have']] },
    stirfry: { title: 'Pork and Bok Choy Stir Fry', description: 'Ground pork, baby bok choy and garlic in a quick ginger-soy sauce over rice.', method: 'Skillet', time: '20 min', healthy: 8, delicious: 7, cost: '~$13', onSale: true, why: ['Quickest option, 20 min', 'Ground pork $2.99/lb, bok choy $1.49', 'Uses rice on hand'], leftovers: 'Fried rice with an egg', ingredients: [['2 lbs', 'ground pork', 'sale'], ['4', 'baby bok choy', 'sale'], ['3 cloves', 'garlic', 'list'], ['2 cups', 'rice', 'have']] },
  },
  slots: [
    { day: 'mon', meal: 'tacos', kind: 'cook', status: 'kept', by: 'Lauren', votes: { lauren: 'up', joe: 'up' } },
    { day: 'tue', kind: 'leftover', text: 'Taco leftovers → taco-salad bowls' },
    { day: 'wed', meal: 'chops', kind: 'cook', status: 'suggested', votes: { joe: 'up' } },
    { day: 'thu', kind: 'leidy', text: 'Leidy cooks', cook: 'Leidy' },
    { day: 'fri', meal: 'shrimp', kind: 'cook', status: 'kept', by: 'Joe', votes: { lauren: 'up', joe: 'up', leidy: 'up' } },
    { day: 'sat', meal: 'chicken', kind: 'cook', status: 'suggested', votes: { lauren: 'up', joe: 'down' } },
    { day: 'sun', kind: 'leftover', text: 'Chicken leftovers → wraps' },
  ],
  alternatives: ['salmon', 'stirfry', 'meatballs', 'soup'],
  rejectReasons: ['Too much work', 'Had it recently', "Kids won't eat it", 'Too pricey', 'Not in the mood', 'Missing equipment'],
  swapPrefs: ['Weekly specials', 'Quicker', 'Lighter', 'Kid-friendly', 'Use what we have', 'Cheaper', 'Different protein'],
  requests: [
    { id: 1, who: 'joe', type: 'meal', text: 'Can we do the basil shrimp again? The kids actually ate it.', when: 'Mon', status: 'planned', reply: 'Planned for Friday' },
    { id: 2, who: 'leidy', type: 'out', text: 'Out of cornstarch and the big yogurt', when: 'Tue', status: 'planned', reply: 'Added to the list' },
    { id: 3, who: 'lauren', type: 'meal', text: 'Something with salmon — it was on sale last time', when: 'Wed', status: 'new' },
    { id: 4, who: 'joe', type: 'out', text: 'Soda water', when: 'Thu', status: 'new' },
    { id: 5, who: 'leidy', type: 'meal', text: 'I can make arroz con pollo Thursday', when: 'Thu', status: 'new' },
  ],
  photos: [
    { src: '../../assets/photos/pantry-1.jpg', label: 'Pantry shelf', meta: 'Today · 9 items' },
    { src: '../../assets/photos/pantry-2.jpg', label: 'Pantry, lower', meta: 'Today · 6 items' },
    { src: '../../assets/photos/pantry-3.jpg', label: 'Freezer', meta: 'Today · 8 items' },
  ],
  pantry: [
    { id: 'p1', area: 'Freezer', name: 'Chicken breasts', qty: '~2 lbs', sure: true },
    { id: 'p2', area: 'Freezer', name: 'Cooked shrimp, 26–30 count', qty: '1 lb bag', sure: true },
    { id: 'p3', area: 'Freezer', name: 'Italian style meatballs', qty: '1 tray', sure: true },
    { id: 'p4', area: 'Freezer', name: 'Peas & carrots', qty: '1 bag', sure: true },
    { id: 'p5', area: 'Freezer', name: 'Ground taco meat?', qty: '1 package', sure: false, note: 'Purple and yellow package, right side' },
    { id: 'p6', area: 'Pantry', name: 'Rice-A-Roni, chicken', qty: '1–2 boxes', sure: false },
    { id: 'p7', area: 'Pantry', name: "Zatarain's yellow rice", qty: '1 box', sure: true },
    { id: 'p8', area: 'Pantry', name: 'Albacore tuna', qty: '1 can', sure: true },
    { id: 'p9', area: 'Pantry', name: 'Barilla spaghetti', qty: '1 box', sure: true },
    { id: 'p10', area: 'Pantry', name: 'Cream of chicken soup', qty: '1 can', sure: true },
  ],
  recipes: [
    { id: 'tacos', title: 'Taco Tuesday', stars: 5, method: 'Skillet', time: '30 min', last: 'Aug 24', tags: ['5 stars', 'Quick'] },
    { id: 'chili', title: "Lauren's Chili", stars: 5, method: 'Le Creuset', time: '60 min', last: 'Feb 23', tags: ['5 stars'] },
    { id: 'soup', title: 'Instant Pot Chicken Tortilla Soup', stars: 5, method: 'Instant Pot', time: '35 min', last: 'Mar 9', tags: ['5 stars', 'Instant Pot'] },
    { id: 'shrimp', title: 'Basil Shrimp with Feta and Orzo', stars: 5, method: 'Skillet', time: '30 min', last: 'Aug 28', tags: ['5 stars', 'Quick'] },
    { id: 'couscous', title: 'Mediterranean Couscous Salad with Grilled Chicken', stars: 4, method: 'Skillet', time: '25 min', last: 'Mar 9', tags: ['Quick'] },
    { id: 'lecreuset', title: 'Le Creuset Chicken', stars: 4, method: 'Le Creuset', time: '45 min', last: 'Jan 30', tags: [] },
    { id: 'arroz', title: 'Arroz con Pollo', stars: 4, method: 'Le Creuset', time: '55 min', last: 'Mar 1', tags: ["Leidy's"] },
    { id: 'meatballs', title: 'Instant Pot Meatballs and Marinara', stars: 3, method: 'Instant Pot', time: '25 min', last: 'Feb 2', tags: ['Instant Pot', 'Quick'] },
  ],
  cart: [
    { id: 'c1', item: '2 lbs pork taco meat', product: 'Cermak Marinated Al Pastor Pork', size: '2 lb', price: 6.98, sure: true },
    { id: 'c2', item: '5 pork chops', product: 'Center Cut Pork Chops, bone-in', size: '2.5 lb', price: 5.73, sure: false, note: 'You usually buy boneless' },
    { id: 'c3', item: '1.5 lbs XL shrimp', product: 'XL Cooked Shrimp 16/20', size: '1.5 lb', price: 14.99, sure: true },
    { id: 'c4', item: '1 queso fresco', product: 'El Mexicano Queso Fresco', size: '10 oz', price: 1.99, sure: true },
    { id: 'c5', item: '1 lb orzo', product: 'Barilla Orzo', size: '16 oz', price: 2.49, sure: true },
    { id: 'c6', item: 'Yogurt', product: 'Chobani Plain Greek Yogurt', size: '32 oz', price: 6.49, sure: false, note: 'Leidy asked for "the big yogurt"' },
  ],
  stores: [
    { id: 'cermak', name: 'Cermak Produce', ad: 'Aug 13–26', deals: 38 },
    { id: 'aldi', name: 'Aldi', ad: 'Aug 20–26', deals: 22 },
    { id: 'amazon', name: 'Amazon Fresh', ad: 'This week', deals: 31 },
  ],
  orderVia: [
    { id: 'delivery', label: 'Instacart delivery', sub: 'Cermak or Aldi · usually Saturday morning', icon: 'truck' },
    { id: 'pickup', label: 'Instacart pickup', sub: 'Ready at the store', icon: 'store' },
    { id: 'amazon', label: 'Amazon delivery', sub: 'Amazon Fresh / Whole Foods', icon: 'package' },
    { id: 'share', label: 'Send the list to someone', sub: 'Text, email or the Notion page', icon: 'send' },
    { id: 'self', label: "We'll shop it ourselves", sub: 'Check off by aisle in the store', icon: 'shopping-basket' },
  ],
  cartMore: 32, cartTotal: 148.2,
  chatStarters: ['Make Thursday vegetarian', 'We have leftover rice', 'Something cheaper than shrimp', 'What can Leidy make?'],
};
