"""initial schema and seed

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 13:48:02.992484
"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime, timezone


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pantry_photos',
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('uploaded_by', sa.String(length=20), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('recipes',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('short_title', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=True),
    sa.Column('prep_min', sa.Integer(), nullable=True),
    sa.Column('cook_min', sa.Integer(), nullable=True),
    sa.Column('total_min', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('healthy', sa.Integer(), nullable=True),
    sa.Column('delicious', sa.Integer(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('leftovers', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_made', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('staples',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('from', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('ads_url', sa.String(length=500), nullable=True),
    sa.Column('instacart_retailer_key', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('cook_log',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('who', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deals',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('item', sa.String(length=200), nullable=False),
    sa.Column('price', sa.String(length=40), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('source_image', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('remember', sa.Boolean(), nullable=False),
    sa.Column('who', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pantry_items',
    sa.Column('area', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('added_by', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['pantry_photos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queue',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('by', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id')
    )
    op.create_table('weeks',
    sa.Column('monday', sa.Date(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('order_via', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=20), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_list', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monday')
    )
    op.create_table('chat_messages',
    sa.Column('who', sa.String(length=20), nullable=False),
    sa.Column('from', sa.String(length=8), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('proposal', sa.JSON(), nullable=True),
    sa.Column('week_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_adds',
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.String(length=80), nullable=True),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('from', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_checks',
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.String(length=200), nullable=False),
    sa.Column('checked_by', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_id', 'item_key', name='uq_list_check_key')
    )
    op.create_table('list_edits',
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_id', 'item_key', name='uq_list_edit_key')
    )
    op.create_table('requests',
    sa.Column('who', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('week_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slots',
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('by', sa.String(length=40), nullable=True),
    sa.Column('basis', sa.Text(), nullable=True),
    sa.Column('why', sa.JSON(), nullable=False),
    sa.Column('cook', sa.String(length=40), nullable=True),
    sa.Column('ingredient_flags', sa.JSON(), nullable=False),
    sa.Column('ingredients_override', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_id', 'day', name='uq_slot_week_day')
    )
    op.create_table('votes',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('person', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=8), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id', 'person', name='uq_vote_slot_person')
    )
    # ### end Alembic commands ###
    _seed()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('slots')
    op.drop_table('requests')
    op.drop_table('list_edits')
    op.drop_table('list_checks')
    op.drop_table('list_adds')
    op.drop_table('chat_messages')
    op.drop_table('weeks')
    op.drop_table('queue')
    op.drop_table('pantry_items')
    op.drop_table('feedback')
    op.drop_table('deals')
    op.drop_table('cook_log')
    op.drop_table('stores')
    op.drop_table('staples')
    op.drop_table('settings')
    op.drop_table('recipes')
    op.drop_table('people')
    op.drop_table('pantry_photos')
    op.drop_table('jobs')
    # ### end Alembic commands ###


MODEL = "claude-sonnet-5-5"


def _seed() -> None:
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    ts = {"created_at": now, "updated_at": now}
    people = sa.table("people", sa.column("key"), sa.column("name"), sa.column("color"),
                      sa.column("created_at"), sa.column("updated_at"))
    op.bulk_insert(people, [
        {"key": "lauren", "name": "Lauren", "color": "sage", **ts},
        {"key": "joe", "name": "Joe", "color": "slate", **ts},
        {"key": "leidy", "name": "Leidy", "color": "terra", **ts},
    ])
    stores = sa.table("stores", sa.column("key"), sa.column("name"), sa.column("ads_url"),
                      sa.column("instacart_retailer_key"), sa.column("created_at"), sa.column("updated_at"))
    op.bulk_insert(stores, [
        {"key": "cermak", "name": "Cermak Produce", "ads_url": "https://www.cermakproduce.com/weekly-ads/",
         "instacart_retailer_key": None, **ts},
        {"key": "aldi", "name": "Aldi", "ads_url": "https://www.aldi.us/weekly-specials/our-weekly-ads/",
         "instacart_retailer_key": None, **ts},
        {"key": "amazon", "name": "Amazon Fresh", "ads_url": None, "instacart_retailer_key": None, **ts},
    ])
    settings = sa.table("settings", sa.column("key"), sa.column("value", sa.JSON),
                        sa.column("created_at"), sa.column("updated_at"))
    defaults = {
        "prep_day": "sat",
        "prep_time": "07:00",
        "leidy_nights": ["thu"],
        "household_size": 5,
        "cook_nights_target": 5,
        "default_store": "cermak",
        "default_order_via": "delivery",
        "models": {k: MODEL for k in ("plan", "swap", "replacement", "pantry", "ads", "recipe", "chat")},
    }
    op.bulk_insert(settings, [{"key": k, "value": v, **ts} for k, v in defaults.items()])
